BOX_IMAGE = "ubuntu/bionic64"

Vagrant.configure("2") do | config |
  config.vm.box = BOX_IMAGE

  config.vm.define "balancer" do | subconfig |
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.hostname = "balancer"
    subconfig.vm.network "forwarded_port", guest: 80, host: 8181
    subconfig.vm.provision "shell", path:"nginx-prov.sh"
  end

  config.vm.define "client1" do | subconfig |
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.hostname = "client1"
    subconfig.vm.network :private_network, ip: "192.168.100.2"
    subconfig.vm.network "forwarded_port", guest: 80, host: 8182
    subconfig.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get install -y nginx
        echo "client1" > /var/www/html/index.nginx-debian.html
        service nginx start
    SHELL
  end

  config.vm.define "client2" do | subconfig |
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.hostname = "client2"
    subconfig.vm.network :private_network, ip: "192.168.100.3"
    subconfig.vm.network "forwarded_port", guest: 80, host: 8183
    subconfig.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get install -y nginx
        echo "client2" > /var/www/html/index.nginx-debian.html
        service nginx start
    SHELL
  end

  config.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.cpus = 1
  end
end